name: Deploy WOL server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Conducting business...
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_TARGET_IP }} << 'EOF'
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh

            cd /production/wake-on-lan

            git pull origin main

            npm install

            npm run build

            rm -rf client docker .gitignore .git .github doc-images servers.yml.example README.md

            cp /config/wake-on-lan/servers.yml /production/wake-on-lan/servers.yml

            pm2 restart wol-server || pm2 start server.js --name "wol-server"
          EOF
